### ISSUE TITLE
implementation of VKMC

### ISSUE THREAD

**Issue by Creazy-MR** [haoyuzhao123/coreset-vfl-codes#1]
In the implementation of VKMC, why the coreset returned by each client is still the sample coreset rather than the so-called indices?

**Comment by haoyuzhao123** [comment]
Hi, in our implementation, we use a single machine to simulate the distributed setting, and thus we do not implement the exact algorithms in our paper, which is much more complicated than the current simulation. The only difference between our implementation and the algorithm shown in the paper is the "communication bits", which don't exist in the single-machine setting.
